{{- range $endpoint := .Values.endpoints }}
{{- range $model := $endpoint.models }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "openai-monitor.fullname" $ }}-{{ $endpoint.name }}-{{ $model.name }}
  labels:
    {{- include "openai-monitor.labels" $ | nindent 4 }}
    endpoint: {{ $endpoint.name }}
    model: {{ $model.name }}
spec:
  schedule: {{ $.Values.cronJob.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            {{- include "openai-monitor.selectorLabels" $ | nindent 12 }}
            endpoint: {{ $endpoint.name }}
            model: {{ $model.name }}
        spec:
          containers:
          - name: monitor
            image: {{ $.Values.cronJob.image.repository }}:{{ $.Values.cronJob.image.tag | default $.Chart.AppVersion }}
            imagePullPolicy: {{ $.Values.cronJob.image.pullPolicy }}
            env:
              - name: SERVER_URL
                value: {{ $endpoint.url | quote }}
              - name: CRONITOR_BASE_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ required "telemetry.secretName is required" $.Values.telemetry.secretName | quote }}
                    key: cronitor-url
                {{- with $.Values.telemetry.secretName }}
              - name: CRONITOR_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ . | quote }}
                    key: cronitor-api-key
                    optional: true
                {{- end }}
              - name: MONITOR_NAME
                value: {{ $model.monitor | default (printf "%s-%s" $endpoint.name $model.name) | quote }}
              {{- with $model.type }}
              - name: ENDPOINT_TYPE
                value: {{ . | quote }}
              {{- end }}
              {{- with $model.name }}
              - name: MODEL_NAME
                value: {{ . | quote }}
              {{- end }}
              {{- with $model.env }}
              - name: APP_ENV
                value: {{ . | quote }}
              {{- end }}
              {{- with $model.timeoutSeconds }}
              - name: TIMEOUT_SECONDS
                value: {{ . | quote }}
              {{- end }}
              {{- with $model.minFreqRequiredMins }}
              - name: MIN_SUCCESS_FREQ
                value: {{ . | quote }}
              {{- end }}
              - name: SCHEDULE
                value: {{$.Values.cronJob.schedule}}
              {{- with $model.consecutiveFailures }}
              - name: CONSECUTIVE_FAILURES_FOR_ALERT
                value: {{ . | quote }}
              {{- end }}
              {{- with $model.consecutiveMissing }}
              - name: CONSECUTIVE_MISSING_FOR_ALERT
                value: {{ . | quote }}
              {{- end }}
              {{- with $model.monitorGroup }}
              - name: MONITOR_GROUP
                value: {{ . | quote }}
              {{- end }}
            {{- with $.Values.cronJob.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          restartPolicy: {{ $.Values.cronJob.restartPolicy }}
{{- end }}
{{- end }}
