{{- if .Values.newman.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-monitor.fullname" . }}
  labels:
    {{- include "model-monitor.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $fileName, $fileContent := .Values.newman.secret.files }}
  {{ $fileName }}: {{ if kindIs "string" $fileContent }}{{ $fileContent | b64enc }}{{ else }}{{ $fileContent | toJson | b64enc }}{{ end }}
{{- end }}
{{- end }}